### ISSUE TITLE
Mentor_me_now app

### ISSUE THREAD

**Issue by martinkarugaba** [martinkarugaba/mentor_me_now_front_end#11]
# About our project

- [x] [Our project](https://github.com/users/martinkarugaba/projects/11/views/1)
- [x] There are three members in our team
- @martinkarugaba 
- @lily4178993 
- @Ayokunnumi1 

![kanban](https://github.com/martinkarugaba/mentor_me_now_front_end/assets/55017675/25284651-2617-413b-9cdf-c9ab772e1dc4)

**Comment by lily4178993** [comment]
Notes to the next reviewer:
We did not receive any comments from the previous reviewer to make the changes.

**Comment by Meltrust** [comment]
## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have descriptions, assignees, and pointings according to spec✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by lily4178993** [comment]
Thank you @Meltrust for the review.
